import { respond } from "@sveltejs/kit/ssr";
import fs from "fs";
import dayjs from "dayjs";
import frontmatter from "remark-frontmatter";
import gfm from "remark-gfm";
import highlight from "rehype-highlight";
import parse from "remark-parse";
import rehypeStringify from "rehype-stringify";
import remark2rehype from "remark-rehype";
import unified from "unified";
import vfile from "to-vfile";
import yaml from "js-yaml";
function run(fn) {
  return fn();
}
function blank_object() {
  return Object.create(null);
}
function run_all(fns) {
  fns.forEach(run);
}
let current_component;
function set_current_component(component) {
  current_component = component;
}
function get_current_component() {
  if (!current_component)
    throw new Error("Function called outside component initialization");
  return current_component;
}
function setContext(key, context) {
  get_current_component().$$.context.set(key, context);
}
Promise.resolve();
const escaped = {
  '"': "&quot;",
  "'": "&#39;",
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;"
};
function escape(html) {
  return String(html).replace(/["'&<>]/g, (match) => escaped[match]);
}
function each(items, fn) {
  let str = "";
  for (let i = 0; i < items.length; i += 1) {
    str += fn(items[i], i);
  }
  return str;
}
const missing_component = {
  $$render: () => ""
};
function validate_component(component, name) {
  if (!component || !component.$$render) {
    if (name === "svelte:component")
      name += " this={...}";
    throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
  }
  return component;
}
let on_destroy;
function create_ssr_component(fn) {
  function $$render(result, props, bindings, slots, context) {
    const parent_component = current_component;
    const $$ = {
      on_destroy,
      context: new Map(parent_component ? parent_component.$$.context : context || []),
      on_mount: [],
      before_update: [],
      after_update: [],
      callbacks: blank_object()
    };
    set_current_component({ $$ });
    const html = fn(result, props, bindings, slots);
    set_current_component(parent_component);
    return html;
  }
  return {
    render: (props = {}, { $$slots = {}, context = new Map() } = {}) => {
      on_destroy = [];
      const result = { title: "", head: "", css: new Set() };
      const html = $$render(result, props, {}, $$slots, context);
      run_all(on_destroy);
      return {
        html,
        css: {
          code: Array.from(result.css).map((css2) => css2.code).join("\n"),
          map: null
        },
        head: result.title + result.head
      };
    },
    $$render
  };
}
function add_attribute(name, value, boolean) {
  if (value == null || boolean && !value)
    return "";
  return ` ${name}${value === true ? "" : `=${typeof value === "string" ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}
function afterUpdate() {
}
var root_svelte_svelte_type_style_lang = "#svelte-announcer.svelte-1j55zn5{position:absolute;left:0;top:0;clip:rect(0 0 0 0);clip-path:inset(50%);overflow:hidden;white-space:nowrap;width:1px;height:1px}";
const css$8 = {
  code: "#svelte-announcer.svelte-1j55zn5{position:absolute;left:0;top:0;clip:rect(0 0 0 0);clip-path:inset(50%);overflow:hidden;white-space:nowrap;width:1px;height:1px}",
  map: `{"version":3,"file":"root.svelte","sources":["root.svelte"],"sourcesContent":["<!-- This file is generated by @sveltejs/kit \u2014 do not edit it! -->\\n<script>\\n\\timport { setContext, afterUpdate, onMount } from 'svelte';\\n\\n\\t// stores\\n\\texport let stores;\\n\\texport let page;\\n\\n\\texport let components;\\n\\texport let props_0 = null;\\n\\texport let props_1 = null;\\n\\texport let props_2 = null;\\n\\n\\tsetContext('__svelte__', stores);\\n\\n\\t$: stores.page.set(page);\\n\\tafterUpdate(stores.page.notify);\\n\\n\\tlet mounted = false;\\n\\tlet navigated = false;\\n\\tlet title = null;\\n\\n\\tonMount(() => {\\n\\t\\tconst unsubscribe = stores.page.subscribe(() => {\\n\\t\\t\\tif (mounted) {\\n\\t\\t\\t\\tnavigated = true;\\n\\t\\t\\t\\ttitle = document.title || 'untitled page';\\n\\t\\t\\t}\\n\\t\\t});\\n\\n\\t\\tmounted = true;\\n\\t\\treturn unsubscribe;\\n\\t});\\n<\/script>\\n\\n<svelte:component this={components[0]} {...(props_0 || {})}>\\n\\t{#if components[1]}\\n\\t\\t<svelte:component this={components[1]} {...(props_1 || {})}>\\n\\t\\t\\t{#if components[2]}\\n\\t\\t\\t\\t<svelte:component this={components[2]} {...(props_2 || {})}/>\\n\\t\\t\\t{/if}\\n\\t\\t</svelte:component>\\n\\t{/if}\\n</svelte:component>\\n\\n{#if mounted}\\n\\t<div id=\\"svelte-announcer\\" aria-live=\\"assertive\\" aria-atomic=\\"true\\">\\n\\t\\t{#if navigated}\\n\\t\\t\\t{title}\\n\\t\\t{/if}\\n\\t</div>\\n{/if}\\n\\n<style>\\n\\t#svelte-announcer {\\n\\t\\tposition: absolute;\\n\\t\\tleft: 0;\\n\\t\\ttop: 0;\\n\\t\\tclip: rect(0 0 0 0);\\n\\t\\tclip-path: inset(50%);\\n\\t\\toverflow: hidden;\\n\\t\\twhite-space: nowrap;\\n\\t\\twidth: 1px;\\n\\t\\theight: 1px;\\n\\t}\\n</style>"],"names":[],"mappings":"AAsDC,iBAAiB,eAAC,CAAC,AAClB,QAAQ,CAAE,QAAQ,CAClB,IAAI,CAAE,CAAC,CACP,GAAG,CAAE,CAAC,CACN,IAAI,CAAE,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CACnB,SAAS,CAAE,MAAM,GAAG,CAAC,CACrB,QAAQ,CAAE,MAAM,CAChB,WAAW,CAAE,MAAM,CACnB,KAAK,CAAE,GAAG,CACV,MAAM,CAAE,GAAG,AACZ,CAAC"}`
};
const Root = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { stores } = $$props;
  let { page } = $$props;
  let { components } = $$props;
  let { props_0 = null } = $$props;
  let { props_1 = null } = $$props;
  let { props_2 = null } = $$props;
  setContext("__svelte__", stores);
  afterUpdate(stores.page.notify);
  if ($$props.stores === void 0 && $$bindings.stores && stores !== void 0)
    $$bindings.stores(stores);
  if ($$props.page === void 0 && $$bindings.page && page !== void 0)
    $$bindings.page(page);
  if ($$props.components === void 0 && $$bindings.components && components !== void 0)
    $$bindings.components(components);
  if ($$props.props_0 === void 0 && $$bindings.props_0 && props_0 !== void 0)
    $$bindings.props_0(props_0);
  if ($$props.props_1 === void 0 && $$bindings.props_1 && props_1 !== void 0)
    $$bindings.props_1(props_1);
  if ($$props.props_2 === void 0 && $$bindings.props_2 && props_2 !== void 0)
    $$bindings.props_2(props_2);
  $$result.css.add(css$8);
  {
    stores.page.set(page);
  }
  return `


${validate_component(components[0] || missing_component, "svelte:component").$$render($$result, Object.assign(props_0 || {}), {}, {
    default: () => `${components[1] ? `${validate_component(components[1] || missing_component, "svelte:component").$$render($$result, Object.assign(props_1 || {}), {}, {
      default: () => `${components[2] ? `${validate_component(components[2] || missing_component, "svelte:component").$$render($$result, Object.assign(props_2 || {}), {}, {})}` : ``}`
    })}` : ``}`
  })}

${``}`;
});
let base = "";
let assets = "";
function set_paths(paths) {
  base = paths.base;
  assets = paths.assets || base;
}
function set_prerendering(value) {
}
var user_hooks = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module"
});
const template = ({ head, body }) => '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <link rel="icon" href="/svelte-kit-blog-demo/favicon.ico" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    ' + head + '\n  </head>\n  <body>\n    <div id="svelte">' + body + "</div>\n  </body>\n</html>\n";
let options = null;
const default_settings = { paths: { "base": "", "assets": "" } };
function init(settings = default_settings) {
  set_paths(settings.paths);
  set_prerendering(settings.prerendering || false);
  const hooks = get_hooks(user_hooks);
  options = {
    amp: false,
    dev: false,
    entry: {
      file: assets + "/internal/start-8cea9b71.js",
      css: [assets + "/internal/assets/start-61d1577b.css"],
      js: [assets + "/internal/start-8cea9b71.js", assets + "/internal/chunks/vendor-d79afd49.js", assets + "/internal/chunks/paths-28a87002.js"]
    },
    fetched: void 0,
    floc: false,
    get_component_path: (id) => assets + "/internal/" + entry_lookup[id],
    get_stack: (error2) => String(error2),
    handle_error: (error2, request) => {
      hooks.handleError({ error: error2, request });
      error2.stack = options.get_stack(error2);
    },
    hooks,
    hydrate: true,
    initiator: void 0,
    load_component,
    manifest,
    paths: settings.paths,
    prerender: true,
    read: settings.read,
    root: Root,
    service_worker: null,
    router: true,
    ssr: true,
    target: "#svelte",
    template,
    trailing_slash: "never"
  };
}
const d = decodeURIComponent;
const empty = () => ({});
const manifest = {
  assets: [{ "file": "favicon.ico", "size": 1150, "type": "image/vnd.microsoft.icon" }, { "file": "favicon.png", "size": 39720, "type": "image/png" }, { "file": "robots.txt", "size": 66, "type": "text/plain" }],
  layout: "src/routes/__layout.svelte",
  error: ".svelte-kit/build/components/error.svelte",
  routes: [
    {
      type: "page",
      pattern: /^\/$/,
      params: empty,
      a: ["src/routes/__layout.svelte", "src/routes/index.svelte"],
      b: [".svelte-kit/build/components/error.svelte"]
    },
    {
      type: "endpoint",
      pattern: /^\/blog\.json$/,
      params: empty,
      load: () => Promise.resolve().then(function() {
        return blog_json;
      })
    },
    {
      type: "endpoint",
      pattern: /^\/images\/dune-otis\/?$/,
      params: empty,
      load: () => Promise.resolve().then(function() {
        return duneOtis$1;
      })
    },
    {
      type: "page",
      pattern: /^\/about\/?$/,
      params: empty,
      a: ["src/routes/__layout.svelte", "src/routes/about.svelte"],
      b: [".svelte-kit/build/components/error.svelte"]
    },
    {
      type: "page",
      pattern: /^\/blog\/?$/,
      params: empty,
      a: ["src/routes/__layout.svelte", "src/routes/blog.svelte"],
      b: [".svelte-kit/build/components/error.svelte"]
    },
    {
      type: "endpoint",
      pattern: /^\/([^/]+?)\.json$/,
      params: (m) => ({ slug: d(m[1]) }),
      load: () => Promise.resolve().then(function() {
        return _slug__json;
      })
    },
    {
      type: "page",
      pattern: /^\/([^/]+?)\/?$/,
      params: (m) => ({ slug: d(m[1]) }),
      a: ["src/routes/__layout.svelte", "src/routes/[slug].svelte"],
      b: [".svelte-kit/build/components/error.svelte"]
    }
  ]
};
const get_hooks = (hooks) => ({
  getSession: hooks.getSession || (() => ({})),
  handle: hooks.handle || (({ request, resolve }) => resolve(request)),
  handleError: hooks.handleError || (({ error: error2 }) => console.error(error2.stack)),
  externalFetch: hooks.externalFetch || fetch
});
const module_lookup = {
  "src/routes/__layout.svelte": () => Promise.resolve().then(function() {
    return __layout;
  }),
  ".svelte-kit/build/components/error.svelte": () => Promise.resolve().then(function() {
    return error;
  }),
  "src/routes/index.svelte": () => Promise.resolve().then(function() {
    return index;
  }),
  "src/routes/about.svelte": () => Promise.resolve().then(function() {
    return about;
  }),
  "src/routes/blog.svelte": () => Promise.resolve().then(function() {
    return blog;
  }),
  "src/routes/[slug].svelte": () => Promise.resolve().then(function() {
    return _slug_;
  })
};
const metadata_lookup = { "src/routes/__layout.svelte": { "entry": "pages/__layout.svelte-88957fb7.js", "css": ["assets/pages/__layout.svelte-37ba07d1.css"], "js": ["pages/__layout.svelte-88957fb7.js", "chunks/vendor-d79afd49.js", "chunks/paths-28a87002.js"], "styles": [] }, ".svelte-kit/build/components/error.svelte": { "entry": "error.svelte-4119af3f.js", "css": [], "js": ["error.svelte-4119af3f.js", "chunks/vendor-d79afd49.js"], "styles": [] }, "src/routes/index.svelte": { "entry": "pages/index.svelte-438ec223.js", "css": ["assets/pages/index.svelte-238e0f1e.css"], "js": ["pages/index.svelte-438ec223.js", "chunks/vendor-d79afd49.js"], "styles": [] }, "src/routes/about.svelte": { "entry": "pages/about.svelte-c2c4656c.js", "css": ["assets/pages/about.svelte-cd99b2c0.css"], "js": ["pages/about.svelte-c2c4656c.js", "chunks/vendor-d79afd49.js"], "styles": [] }, "src/routes/blog.svelte": { "entry": "pages/blog.svelte-148c27c9.js", "css": ["assets/pages/blog.svelte-017a6d66.css"], "js": ["pages/blog.svelte-148c27c9.js", "chunks/vendor-d79afd49.js", "chunks/paths-28a87002.js"], "styles": [] }, "src/routes/[slug].svelte": { "entry": "pages/[slug].svelte-8743bf44.js", "css": ["assets/pages/[slug].svelte-ecef8022.css"], "js": ["pages/[slug].svelte-8743bf44.js", "chunks/vendor-d79afd49.js", "chunks/paths-28a87002.js"], "styles": [] } };
async function load_component(file) {
  const { entry, css: css2, js, styles } = metadata_lookup[file];
  return {
    module: await module_lookup[file](),
    entry: assets + "/internal/" + entry,
    css: css2.map((dep) => assets + "/internal/" + dep),
    js: js.map((dep) => assets + "/internal/" + dep),
    styles
  };
}
function render(request, {
  prerender
} = {}) {
  const host = request.headers["host"];
  return respond({ ...request, host }, options, { prerender });
}
let parser = unified().use(parse).use(gfm).use(frontmatter, ["yaml"]);
let runner = unified().use(remark2rehype).use(highlight).use(rehypeStringify);
function process(filename) {
  let tree = parser.parse(vfile.readSync(filename));
  let metadata = null;
  if (tree.children.length > 0 && tree.children[0].type == "yaml") {
    metadata = yaml.load(tree.children[0].value);
    tree.children = tree.children.slice(1, tree.children.length);
    metadata.date = dayjs(metadata.date).format("MMM D, YYYY");
  }
  let content = runner.stringify(runner.runSync(tree));
  if (!metadata) {
    metadata = {
      title: "Error!",
      date: "?",
      excerpt: "Missing Frontmatter! Expected at least a title and a date!"
    };
    content = "Missing Frontmatter! Expected at least a title and a date!";
  }
  return { metadata, content };
}
function get$1() {
  let posts = fs.readdirSync(`src/posts`).filter((fileName) => /.+\.md$/.test(fileName)).map((fileName) => {
    const { metadata } = process(`src/posts/${fileName}`);
    return {
      metadata,
      slug: fileName.slice(0, -3)
    };
  });
  posts.sort((a, b) => dayjs(a.metadata.date, "MMM D, YYYY") - dayjs(b.metadata.date, "MMM D, YYYY"));
  let body = JSON.stringify(posts);
  return {
    body
  };
}
var blog_json = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  get: get$1
});
var duneOtis = "/internal/assets/dune-otis-28139fc8.jpg";
var duneOtis$1 = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  "default": duneOtis
});
function get({ params }) {
  const { slug } = params;
  const { metadata, content } = process(`src/posts/${slug}.md`);
  const body = JSON.stringify({ metadata, content });
  return {
    body
  };
}
var _slug__json = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  get
});
var app = 'body {\n  margin: 0;\n}\n\nh1,\nh2,\nh3,\nh4,\np,\na,\nul {\n  font-family: "Oxygen", sans-serif;\n  font-weight: 400;\n}\n\na {\n  color: #e23500;\n  text-decoration: none;\n}\na:hover {\n  color: #f58b12;\n}\n\ncode {\n  font-family: "Fira Mono", monospace !important;\n  font-size: 14px;\n  font-weight: 400;\n}\n\nh1 {\n  font-size: 40px;\n  color: #333;\n}\n\nh2 {\n  font-size: 26px;\n  color: #333;\n}\n\nh3 {\n  font-size: 22px;\n  color: #222;\n}\n\np,\nul {\n  font-size: 18px;\n  color: #444;\n}';
var Nav_svelte_svelte_type_style_lang = "nav.svelte-1pzvsga{background:linear-gradient(72deg, #e23500, #ffbc2d);display:flex;justify-content:space-between;align-content:center;height:78px;padding:0 20%}a.svelte-1pzvsga{text-decoration:none}h3.svelte-1pzvsga{margin-bottom:0px;color:white;font-weight:400}h3.svelte-1pzvsga:hover{text-decoration:underline}";
const css$7 = {
  code: "nav.svelte-1pzvsga{background:linear-gradient(72deg, #e23500, #ffbc2d);display:flex;justify-content:space-between;align-content:center;height:78px;padding:0 20%}a.svelte-1pzvsga{text-decoration:none}h3.svelte-1pzvsga{margin-bottom:0px;color:white;font-weight:400}h3.svelte-1pzvsga:hover{text-decoration:underline}",
  map: '{"version":3,"file":"Nav.svelte","sources":["Nav.svelte"],"sourcesContent":["<script>\\n  import { base } from \\"$app/paths\\";\\n<\/script>\\n\\n<div>\\n  <nav>\\n    <a href=\\"{base}/\\"><h3 class=\\"home\\">home</h3></a>\\n    <a href=\\"{base}/blog\\"><h3 class=\\"blog\\">blog</h3></a>\\n    <a href=\\"{base}/about\\"><h3 class=\\"about\\">about</h3></a>\\n  </nav>\\n</div>\\n\\n<style lang=\\"scss\\">nav {\\n  background: linear-gradient(72deg, #e23500, #ffbc2d);\\n  display: flex;\\n  justify-content: space-between;\\n  align-content: center;\\n  height: 78px;\\n  padding: 0 20%;\\n}\\n\\na {\\n  text-decoration: none;\\n}\\n\\nh3 {\\n  margin-bottom: 0px;\\n  color: white;\\n  font-weight: 400;\\n}\\nh3:hover {\\n  text-decoration: underline;\\n}</style>\\n"],"names":[],"mappings":"AAYmB,GAAG,eAAC,CAAC,AACtB,UAAU,CAAE,gBAAgB,KAAK,CAAC,CAAC,OAAO,CAAC,CAAC,OAAO,CAAC,CACpD,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,aAAa,CAC9B,aAAa,CAAE,MAAM,CACrB,MAAM,CAAE,IAAI,CACZ,OAAO,CAAE,CAAC,CAAC,GAAG,AAChB,CAAC,AAED,CAAC,eAAC,CAAC,AACD,eAAe,CAAE,IAAI,AACvB,CAAC,AAED,EAAE,eAAC,CAAC,AACF,aAAa,CAAE,GAAG,CAClB,KAAK,CAAE,KAAK,CACZ,WAAW,CAAE,GAAG,AAClB,CAAC,AACD,iBAAE,MAAM,AAAC,CAAC,AACR,eAAe,CAAE,SAAS,AAC5B,CAAC"}'
};
const Nav = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$7);
  return `<div><nav class="${"svelte-1pzvsga"}"><a href="${escape(base) + "/"}" class="${"svelte-1pzvsga"}"><h3 class="${"home svelte-1pzvsga"}">home</h3></a>
    <a href="${escape(base) + "/blog"}" class="${"svelte-1pzvsga"}"><h3 class="${"blog svelte-1pzvsga"}">blog</h3></a>
    <a href="${escape(base) + "/about"}" class="${"svelte-1pzvsga"}"><h3 class="${"about svelte-1pzvsga"}">about</h3></a></nav>
</div>`;
});
const Icon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { name } = $$props;
  let { width = "1rem" } = $$props;
  let { height = "1rem" } = $$props;
  let { focusable = false } = $$props;
  let icons = [
    {
      box: 24,
      name: "twitter",
      svg: `<path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/>`
    },
    {
      box: 24,
      name: "paperplane",
      svg: `<path d="M24 0l-6 22-8.129-7.239 7.802-8.234-10.458 7.227-7.215-1.754 24-12zm-15 16.668v7.332l3.258-4.431-3.258-2.901z"/>`
    },
    {
      box: 24,
      name: "linkedin",
      svg: `<path d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z"/>`
    },
    {
      box: 24,
      name: "instagram",
      svg: `<path d="M11.984 16.815c2.596 0 4.706-2.111 4.706-4.707 0-1.409-.623-2.674-1.606-3.538-.346-.303-.735-.556-1.158-.748-.593-.27-1.249-.421-1.941-.421s-1.349.151-1.941.421c-.424.194-.814.447-1.158.749-.985.864-1.608 2.129-1.608 3.538 0 2.595 2.112 4.706 4.706 4.706zm.016-8.184c1.921 0 3.479 1.557 3.479 3.478 0 1.921-1.558 3.479-3.479 3.479s-3.479-1.557-3.479-3.479c0-1.921 1.558-3.478 3.479-3.478zm5.223.369h6.777v10.278c0 2.608-2.114 4.722-4.722 4.722h-14.493c-2.608 0-4.785-2.114-4.785-4.722v-10.278h6.747c-.544.913-.872 1.969-.872 3.109 0 3.374 2.735 6.109 6.109 6.109s6.109-2.735 6.109-6.109c.001-1.14-.327-2.196-.87-3.109zm2.055-9h-12.278v5h-1v-5h-1v5h-1v-4.923c-.346.057-.682.143-1 .27v4.653h-1v-4.102c-1.202.857-2 2.246-2 3.824v3.278h7.473c1.167-1.282 2.798-2 4.511-2 1.722 0 3.351.725 4.511 2h7.505v-3.278c0-2.608-2.114-4.722-4.722-4.722zm2.722 5.265c0 .406-.333.735-.745.735h-2.511c-.411 0-.744-.329-.744-.735v-2.53c0-.406.333-.735.744-.735h2.511c.412 0 .745.329.745.735v2.53z"/>`
    }
  ];
  let displayIcon = icons.find((e) => e.name === name);
  if ($$props.name === void 0 && $$bindings.name && name !== void 0)
    $$bindings.name(name);
  if ($$props.width === void 0 && $$bindings.width && width !== void 0)
    $$bindings.width(width);
  if ($$props.height === void 0 && $$bindings.height && height !== void 0)
    $$bindings.height(height);
  if ($$props.focusable === void 0 && $$bindings.focusable && focusable !== void 0)
    $$bindings.focusable(focusable);
  return `<svg${add_attribute("class", $$props.class, 0)}${add_attribute("title", $$props.description, 0)}${add_attribute("focusable", focusable, 0)}${add_attribute("width", width, 0)}${add_attribute("height", height, 0)} viewBox="${"0 0 " + escape(displayIcon.box) + " " + escape(displayIcon.box)}"><!-- HTML_TAG_START -->${displayIcon.svg}<!-- HTML_TAG_END --></svg>`;
});
var Footer_svelte_svelte_type_style_lang = ".footer.svelte-1ts4n1w{position:fixed;bottom:0;width:100%;display:flex;justify-content:center;align-items:center}.links.svelte-1ts4n1w{justify-content:center;padding-bottom:1.7rem}a.svelte-1ts4n1w{font-size:14px;margin:0 2rem;opacity:0.5}a.svelte-1ts4n1w:hover{opacity:1}";
const css$6 = {
  code: ".footer.svelte-1ts4n1w{position:fixed;bottom:0;width:100%;display:flex;justify-content:center;align-items:center}.links.svelte-1ts4n1w{justify-content:center;padding-bottom:1.7rem}a.svelte-1ts4n1w{font-size:14px;margin:0 2rem;opacity:0.5}a.svelte-1ts4n1w:hover{opacity:1}",
  map: '{"version":3,"file":"Footer.svelte","sources":["Footer.svelte"],"sourcesContent":["<script>\\n  import Icon from \\"$lib/Icon.svelte\\";\\n<\/script>\\n\\n<div class=\\"footer\\">\\n  <div class=\\"links\\">\\n    <a href=\\"mailto:kylie@kyliestewart.tech\\">\\n      <Icon name=\\"paperplane\\" desription=\\"Click here to send Kylie an email.\\" />\\n    </a>\\n    <a href=\\"http://linkedin.com/in/kylieastewart\\"\\n      ><Icon\\n        name=\\"linkedin\\"\\n        description=\\"Click here to connect with Kylie on LinkedIn.\\"\\n      /></a\\n    >\\n    <a href=\\"www.twitter.com/kyliestew\\"\\n      ><Icon\\n        name=\\"twitter\\"\\n        description=\\"Click here to follow Kylie on Twitter.\\"\\n      /></a\\n    >\\n    <a href=\\"http://instagram.com/kalestews\\"\\n      ><Icon\\n        name=\\"instagram\\"\\n        description=\\"Click here to follow Kylie on Instagram.\\"\\n      /></a\\n    >\\n  </div>\\n</div>\\n\\n<style lang=\\"scss\\">.footer {\\n  position: fixed;\\n  bottom: 0;\\n  width: 100%;\\n  display: flex;\\n  justify-content: center;\\n  align-items: center;\\n}\\n\\n.links {\\n  justify-content: center;\\n  padding-bottom: 1.7rem;\\n}\\n\\na {\\n  font-size: 14px;\\n  margin: 0 2rem;\\n  opacity: 0.5;\\n}\\na:hover {\\n  opacity: 1;\\n}</style>\\n"],"names":[],"mappings":"AA8BmB,OAAO,eAAC,CAAC,AAC1B,QAAQ,CAAE,KAAK,CACf,MAAM,CAAE,CAAC,CACT,KAAK,CAAE,IAAI,CACX,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,MAAM,AACrB,CAAC,AAED,MAAM,eAAC,CAAC,AACN,eAAe,CAAE,MAAM,CACvB,cAAc,CAAE,MAAM,AACxB,CAAC,AAED,CAAC,eAAC,CAAC,AACD,SAAS,CAAE,IAAI,CACf,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,OAAO,CAAE,GAAG,AACd,CAAC,AACD,gBAAC,MAAM,AAAC,CAAC,AACP,OAAO,CAAE,CAAC,AACZ,CAAC"}'
};
const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$6);
  return `<div class="${"footer svelte-1ts4n1w"}"><div class="${"links svelte-1ts4n1w"}"><a href="${"mailto:kylie@kyliestewart.tech"}" class="${"svelte-1ts4n1w"}">${validate_component(Icon, "Icon").$$render($$result, {
    name: "paperplane",
    desription: "Click here to send Kylie an email."
  }, {}, {})}</a>
    <a href="${"http://linkedin.com/in/kylieastewart"}" class="${"svelte-1ts4n1w"}">${validate_component(Icon, "Icon").$$render($$result, {
    name: "linkedin",
    description: "Click here to connect with Kylie on LinkedIn."
  }, {}, {})}</a>
    <a href="${"www.twitter.com/kyliestew"}" class="${"svelte-1ts4n1w"}">${validate_component(Icon, "Icon").$$render($$result, {
    name: "twitter",
    description: "Click here to follow Kylie on Twitter."
  }, {}, {})}</a>
    <a href="${"http://instagram.com/kalestews"}" class="${"svelte-1ts4n1w"}">${validate_component(Icon, "Icon").$$render($$result, {
    name: "instagram",
    description: "Click here to follow Kylie on Instagram."
  }, {}, {})}</a></div>
</div>`;
});
var __layout_svelte_svelte_type_style_lang = ".g-content-wrapper.svelte-1c6jjpl{padding:0 20%;position:absolute;top:78px;bottom:20px}";
const css$5 = {
  code: ".g-content-wrapper.svelte-1c6jjpl{padding:0 20%;position:absolute;top:78px;bottom:20px}",
  map: '{"version":3,"file":"__layout.svelte","sources":["__layout.svelte"],"sourcesContent":["<script>\\n  import \\"../app.scss\\";\\n  import Nav from \\"$lib/Nav.svelte\\";\\n  import Footer from \\"$lib/Footer.svelte\\";\\n<\/script>\\n\\n<svelte:head>\\n  <link\\n    rel=\\"stylesheet\\"\\n    href=\\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.1/styles/github.min.css\\"\\n  />\\n  <link\\n    rel=\\"stylesheet\\"\\n    href=\\"https://fonts.googleapis.com/css2?family=Oxygen\\"\\n  />\\n  <link\\n    rel=\\"stylesheet\\"\\n    href=\\"https://fonts.googleapis.com/css2?family=Fira+Mono\\"\\n  />\\n</svelte:head>\\n\\n<Nav />\\n<div class=\\"g-content-wrapper\\">\\n  <slot />\\n</div>\\n<Footer />\\n\\n<style lang=\\"scss\\">.g-content-wrapper {\\n  padding: 0 20%;\\n  position: absolute;\\n  top: 78px;\\n  bottom: 20px;\\n}</style>\\n"],"names":[],"mappings":"AA2BmB,kBAAkB,eAAC,CAAC,AACrC,OAAO,CAAE,CAAC,CAAC,GAAG,CACd,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,IAAI,CACT,MAAM,CAAE,IAAI,AACd,CAAC"}'
};
const _layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$5);
  return `${$$result.head += `<link rel="${"stylesheet"}" href="${"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.1/styles/github.min.css"}" data-svelte="svelte-b0idxc"><link rel="${"stylesheet"}" href="${"https://fonts.googleapis.com/css2?family=Oxygen"}" data-svelte="svelte-b0idxc"><link rel="${"stylesheet"}" href="${"https://fonts.googleapis.com/css2?family=Fira+Mono"}" data-svelte="svelte-b0idxc">`, ""}

${validate_component(Nav, "Nav").$$render($$result, {}, {}, {})}
<div class="${"g-content-wrapper svelte-1c6jjpl"}">${slots.default ? slots.default({}) : ``}</div>
${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})}`;
});
var __layout = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  "default": _layout
});
function load$2({ error: error2, status }) {
  return { props: { error: error2, status } };
}
const Error$1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { status } = $$props;
  let { error: error2 } = $$props;
  if ($$props.status === void 0 && $$bindings.status && status !== void 0)
    $$bindings.status(status);
  if ($$props.error === void 0 && $$bindings.error && error2 !== void 0)
    $$bindings.error(error2);
  return `<h1>${escape(status)}</h1>

<pre>${escape(error2.message)}</pre>



${error2.frame ? `<pre>${escape(error2.frame)}</pre>` : ``}
${error2.stack ? `<pre>${escape(error2.stack)}</pre>` : ``}`;
});
var error = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  "default": Error$1,
  load: load$2
});
var Card_svelte_svelte_type_style_lang = ".card.svelte-hqmyl9{padding:12;margin:1rem 3rem}p.svelte-hqmyl9{margin-bottom:0.45rem}";
const css$4 = {
  code: ".card.svelte-hqmyl9{padding:12;margin:1rem 3rem}p.svelte-hqmyl9{margin-bottom:0.45rem}",
  map: '{"version":3,"file":"Card.svelte","sources":["Card.svelte"],"sourcesContent":["<div class=\\"card\\">\\n  <h3>{$$props.title}</h3>\\n  <p>{$$props.subtitle}</p>\\n  <a href={$$props.link}> Go to \u2197 </a>\\n</div>\\n\\n<style>\\n  .card {\\n    padding: 12;\\n    margin: 1rem 3rem;\\n  }\\n\\n  p {\\n    margin-bottom: 0.45rem;\\n  }\\n</style>\\n"],"names":[],"mappings":"AAOE,KAAK,cAAC,CAAC,AACL,OAAO,CAAE,EAAE,CACX,MAAM,CAAE,IAAI,CAAC,IAAI,AACnB,CAAC,AAED,CAAC,cAAC,CAAC,AACD,aAAa,CAAE,OAAO,AACxB,CAAC"}'
};
const Card = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$4);
  return `<div class="${"card svelte-hqmyl9"}"><h3>${escape($$props.title)}</h3>
  <p class="${"svelte-hqmyl9"}">${escape($$props.subtitle)}</p>
  <a${add_attribute("href", $$props.link, 0)}>Go to \u2197 </a>
</div>`;
});
var index_svelte_svelte_type_style_lang = ".cards.svelte-1ixjcwm{display:flex}.intro.svelte-1ixjcwm{display:flex;flex-direction:column;justify-content:center;align-items:center}";
const css$3 = {
  code: ".cards.svelte-1ixjcwm{display:flex}.intro.svelte-1ixjcwm{display:flex;flex-direction:column;justify-content:center;align-items:center}",
  map: '{"version":3,"file":"index.svelte","sources":["index.svelte"],"sourcesContent":["<script>\\n  import Card from \\"$lib/Card.svelte\\";\\n  import { update_slot } from \\"svelte/internal\\";\\n<\/script>\\n\\n<svelte:head>\\n  <title>kylieis.online \xB7 Home</title>\\n</svelte:head>\\n\\n<div class=\\"intro\\">\\n  <h1>Kylie is \u2728 Online \u2728</h1>\\n  <p>Hello and welcome!</p>\\n</div>\\n\\n<div class=\\"cards\\">\\n  <Card\\n    title=\\"Talks\\"\\n    subtitle=\\"All of my talks, in one place.\\"\\n    link=\\"www.kylieis.online/talks\\"\\n  />\\n\\n  <Card\\n    title=\\"kylies.photos\\"\\n    subtitle=\\"Hiking photos and trip reports.\\"\\n    link=\\"www.kylies.photos\\"\\n  />\\n\\n  <Card\\n    title=\\"Now\\"\\n    subtitle=\\"Recent life updates.\\"\\n    link=\\"www.kylieis.online/now\\"\\n  />\\n</div>\\n\\n<style lang=\\"scss\\">.cards {\\n  display: flex;\\n}\\n\\n.intro {\\n  display: flex;\\n  flex-direction: column;\\n  justify-content: center;\\n  align-items: center;\\n}</style>\\n"],"names":[],"mappings":"AAkCmB,MAAM,eAAC,CAAC,AACzB,OAAO,CAAE,IAAI,AACf,CAAC,AAED,MAAM,eAAC,CAAC,AACN,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MAAM,CACtB,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,MAAM,AACrB,CAAC"}'
};
const Routes = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$3);
  return `${$$result.head += `${$$result.title = `<title>kylieis.online \xB7 Home</title>`, ""}`, ""}

<div class="${"intro svelte-1ixjcwm"}"><h1>Kylie is \u2728 Online \u2728</h1>
  <p>Hello and welcome!</p></div>

<div class="${"cards svelte-1ixjcwm"}">${validate_component(Card, "Card").$$render($$result, {
    title: "Talks",
    subtitle: "All of my talks, in one place.",
    link: "www.kylieis.online/talks"
  }, {}, {})}

  ${validate_component(Card, "Card").$$render($$result, {
    title: "kylies.photos",
    subtitle: "Hiking photos and trip reports.",
    link: "www.kylies.photos"
  }, {}, {})}

  ${validate_component(Card, "Card").$$render($$result, {
    title: "Now",
    subtitle: "Recent life updates.",
    link: "www.kylieis.online/now"
  }, {}, {})}
</div>`;
});
var index = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  "default": Routes
});
var about_svelte_svelte_type_style_lang = ".gallery-wrapper.svelte-mrw18n{padding:1.4rem 0 5rem 0}";
const css$2 = {
  code: ".gallery-wrapper.svelte-mrw18n{padding:1.4rem 0 5rem 0}",
  map: `{"version":3,"file":"about.svelte","sources":["about.svelte"],"sourcesContent":["<script>\\n  const Gallery = require(\\"svelte-image-gallery\\");\\n\\n  function handleClick(e) {\\n    console.log(e.detail.url);\\n  }\\n<\/script>\\n\\n<svelte:head>\\n  <title>kylieis.online \xB7 About</title>\\n</svelte:head>\\n\\n<h1>About Kylie</h1>\\n\\n<p>\\n  \u{1F44B} <b>Hi!</b> I'm Kylie Stewart, a freelance consultant based in Georgetown, Colorado.\\n</p>\\n\\n<p>\\n  Currently, I am an enthusiastic <a href=\\"www.notion.com\\">Notion</a>\\n  Ambassador that works as a freelance solutions engineer and web developer. If you'd\\n  like to discuss what working together might look like, please\\n  <a href=\\"mailto:kylie@kyliestewart.tech\\">send me an email</a>!\\n</p>\\n\\n<p>\\n  When I'm not on the clock, I spend my time pursuing Colorado's 100 Highest\\n  Peaks (otherwise known as the Centennials)- often with my fianc\xE9, Kyle, and\\n  our dog, Otis, both of who are pictured below. I'm about halfway through these\\n  summits so far!\\n</p>\\n\\n<p>\\n  Prior to freelancing, I was a software engineer and open-source maintainer at\\n  a Seattle-based Javascript consultancy named <a href=\\"www.formidable.com\\"\\n    >Formidable</a\\n  >. Before I worked in technology at all, I was a Store Coordinator at\\n  <a href=\\"www.tesla.com\\">Tesla</a>, a Volunteer Coordinator for a Denver-based\\n  housing non-profit, and a sommelier-certified bartender.\\n</p>\\n\\n<div class=\\"gallery-wrapper\\">\\n  <Gallery on:click={handleClick}>\\n    <img\\n      alt=\\"Kylie & Kyle standing on a rocky ledge, overlooking a lake with a hazy view of some mountains beyond that.\\"\\n      src=\\"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/fd71de1a-51d6-41ee-96bf-d77b4bb73ce5/54A7F038-B974-4EAD-B8B1-1571F9D5CE28.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T235439Z&X-Amz-Expires=86400&X-Amz-Signature=335ec385f21a2d120b71df4b1179d950d18a36372d9bc70bc611ae548e21e6a1&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%2254A7F038-B974-4EAD-B8B1-1571F9D5CE28.jpeg%22\\"\\n    />\\n    <img\\n      alt=\\"A mostly black dog with a white spot on his chest and down his nose, Otis, sitting in a pile of autumn leaves with a single fall leaf resting on the tip of his nose.\\"\\n      src=\\"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/dc160768-bda5-49b5-92ed-b5428dde535d/63EC7503-13E3-4B61-B0F7-2F70D9FD45B2.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T235118Z&X-Amz-Expires=86400&X-Amz-Signature=ea64caf59f8e9642b0bee2ed96c091874d5a97d57a56d3cac664f095fccdad8e&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%2263EC7503-13E3-4B61-B0F7-2F70D9FD45B2.jpeg%22\\"\\n    />\\n    <img\\n      alt=\\"A man, Kyle, wearing a hat with a ponytail seen underneath it, facing to look out over a rugged red rock valley.\\"\\n      src=\\"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/e7b26b4d-e214-435d-b166-b8eeae77b143/A08AAFD9-CFBC-4BF5-BA4C-A58D5085ADD3.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T234209Z&X-Amz-Expires=86400&X-Amz-Signature=8c43e172f7dd0d2a7de86ac3fe6b481e717f31ae63b372bb863ed8cceb65ca73&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22A08AAFD9-CFBC-4BF5-BA4C-A58D5085ADD3.jpeg%22\\"\\n    />\\n    <img\\n      alt=\\"A mountain goat looking directly at the camera, standing on red rocks.\\"\\n      src=\\"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/50b50a52-7345-4df9-a561-04d7c56d6816/C80ABC69-8C7C-47E3-AF9A-2E3D7B106067.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T235051Z&X-Amz-Expires=86400&X-Amz-Signature=60f23fabca7c3b12eef1f7da44e8f63044ae3bd1ffb35151dfa7965bcaa05f2b&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22C80ABC69-8C7C-47E3-AF9A-2E3D7B106067.jpeg%22\\"\\n    />\\n    <img\\n      alt=\\"Kylie with a helemt on, standing with her hands and feet touching the knife edge below her, smiling.\\"\\n      src=\\"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/048db0f7-12a7-431e-a0ad-7a58b049915d/F4F03D7A-083E-4D77-A0E3-0654140B4B70.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T234228Z&X-Amz-Expires=86400&X-Amz-Signature=642a3bfcbad734f01a4736e6e93266668bb39c5c88ee13ddefd7660bff0f6ff1&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22F4F03D7A-083E-4D77-A0E3-0654140B4B70.jpeg%22\\"\\n    />\\n    <img\\n      alt=\\"Kylie, standing on a small rocky spot, facing towards a larger peak with clouds beginning to encompass the summit.\\"\\n      src=\\"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/019154d9-c564-459f-89c7-ce675228105a/DD99DA25-601C-4D57-9D61-2F6C4D001317.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T234220Z&X-Amz-Expires=86400&X-Amz-Signature=3c726858c7c69c42a1e866921d796223df04ac05f1fd592911aeeded81f4f864&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22DD99DA25-601C-4D57-9D61-2F6C4D001317.jpeg%22\\"\\n    />\\n  </Gallery>\\n</div>\\n\\n<style lang=\\"scss\\">.gallery-wrapper {\\n  padding: 1.4rem 0 5rem 0;\\n}</style>\\n"],"names":[],"mappings":"AAsEmB,gBAAgB,cAAC,CAAC,AACnC,OAAO,CAAE,MAAM,CAAC,CAAC,CAAC,IAAI,CAAC,CAAC,AAC1B,CAAC"}`
};
const About = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  const Gallery = require("svelte-image-gallery");
  $$result.css.add(css$2);
  return `${$$result.head += `${$$result.title = `<title>kylieis.online \xB7 About</title>`, ""}`, ""}

<h1>About Kylie</h1>

<p>\u{1F44B} <b>Hi!</b> I&#39;m Kylie Stewart, a freelance consultant based in Georgetown, Colorado.
</p>

<p>Currently, I am an enthusiastic <a href="${"www.notion.com"}">Notion</a>
  Ambassador that works as a freelance solutions engineer and web developer. If you&#39;d
  like to discuss what working together might look like, please
  <a href="${"mailto:kylie@kyliestewart.tech"}">send me an email</a>!
</p>

<p>When I&#39;m not on the clock, I spend my time pursuing Colorado&#39;s 100 Highest
  Peaks (otherwise known as the Centennials)- often with my fianc\xE9, Kyle, and
  our dog, Otis, both of who are pictured below. I&#39;m about halfway through these
  summits so far!
</p>

<p>Prior to freelancing, I was a software engineer and open-source maintainer at
  a Seattle-based Javascript consultancy named <a href="${"www.formidable.com"}">Formidable</a>. Before I worked in technology at all, I was a Store Coordinator at
  <a href="${"www.tesla.com"}">Tesla</a>, a Volunteer Coordinator for a Denver-based
  housing non-profit, and a sommelier-certified bartender.
</p>

<div class="${"gallery-wrapper svelte-mrw18n"}">${validate_component(Gallery, "Gallery").$$render($$result, {}, {}, {
    default: () => `<img alt="${"Kylie & Kyle standing on a rocky ledge, overlooking a lake with a hazy view of some mountains beyond that."}" src="${"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/fd71de1a-51d6-41ee-96bf-d77b4bb73ce5/54A7F038-B974-4EAD-B8B1-1571F9D5CE28.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T235439Z&X-Amz-Expires=86400&X-Amz-Signature=335ec385f21a2d120b71df4b1179d950d18a36372d9bc70bc611ae548e21e6a1&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%2254A7F038-B974-4EAD-B8B1-1571F9D5CE28.jpeg%22"}">
    <img alt="${"A mostly black dog with a white spot on his chest and down his nose, Otis, sitting in a pile of autumn leaves with a single fall leaf resting on the tip of his nose."}" src="${"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/dc160768-bda5-49b5-92ed-b5428dde535d/63EC7503-13E3-4B61-B0F7-2F70D9FD45B2.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T235118Z&X-Amz-Expires=86400&X-Amz-Signature=ea64caf59f8e9642b0bee2ed96c091874d5a97d57a56d3cac664f095fccdad8e&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%2263EC7503-13E3-4B61-B0F7-2F70D9FD45B2.jpeg%22"}">
    <img alt="${"A man, Kyle, wearing a hat with a ponytail seen underneath it, facing to look out over a rugged red rock valley."}" src="${"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/e7b26b4d-e214-435d-b166-b8eeae77b143/A08AAFD9-CFBC-4BF5-BA4C-A58D5085ADD3.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T234209Z&X-Amz-Expires=86400&X-Amz-Signature=8c43e172f7dd0d2a7de86ac3fe6b481e717f31ae63b372bb863ed8cceb65ca73&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22A08AAFD9-CFBC-4BF5-BA4C-A58D5085ADD3.jpeg%22"}">
    <img alt="${"A mountain goat looking directly at the camera, standing on red rocks."}" src="${"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/50b50a52-7345-4df9-a561-04d7c56d6816/C80ABC69-8C7C-47E3-AF9A-2E3D7B106067.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T235051Z&X-Amz-Expires=86400&X-Amz-Signature=60f23fabca7c3b12eef1f7da44e8f63044ae3bd1ffb35151dfa7965bcaa05f2b&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22C80ABC69-8C7C-47E3-AF9A-2E3D7B106067.jpeg%22"}">
    <img alt="${"Kylie with a helemt on, standing with her hands and feet touching the knife edge below her, smiling."}" src="${"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/048db0f7-12a7-431e-a0ad-7a58b049915d/F4F03D7A-083E-4D77-A0E3-0654140B4B70.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T234228Z&X-Amz-Expires=86400&X-Amz-Signature=642a3bfcbad734f01a4736e6e93266668bb39c5c88ee13ddefd7660bff0f6ff1&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22F4F03D7A-083E-4D77-A0E3-0654140B4B70.jpeg%22"}">
    <img alt="${"Kylie, standing on a small rocky spot, facing towards a larger peak with clouds beginning to encompass the summit."}" src="${"https://s3.us-west-2.amazonaws.com/secure.notion-static.com/019154d9-c564-459f-89c7-ce675228105a/DD99DA25-601C-4D57-9D61-2F6C4D001317.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210820%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210820T234220Z&X-Amz-Expires=86400&X-Amz-Signature=3c726858c7c69c42a1e866921d796223df04ac05f1fd592911aeeded81f4f864&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22DD99DA25-601C-4D57-9D61-2F6C4D001317.jpeg%22"}">`
  })}
</div>`;
});
var about = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  "default": About
});
var blog_svelte_svelte_type_style_lang = "h2.title.svelte-mnabfq{margin-top:2rem;margin-bottom:0.4rem}h2.title.svelte-mnabfq:hover{color:#f58b12}h4.svelte-mnabfq{font-size:17px;color:#555}.labels.svelte-mnabfq{display:flex;font-size:13.5px;margin-top:0px;padding:1px 0 0 4px}p.svelte-mnabfq{color:#777}p.excerpt.svelte-mnabfq{font-style:italic;margin-top:0.2rem;padding-left:4px;max-width:37rem}";
const css$1 = {
  code: "h2.title.svelte-mnabfq{margin-top:2rem;margin-bottom:0.4rem}h2.title.svelte-mnabfq:hover{color:#f58b12}h4.svelte-mnabfq{font-size:17px;color:#555}.labels.svelte-mnabfq{display:flex;font-size:13.5px;margin-top:0px;padding:1px 0 0 4px}p.svelte-mnabfq{color:#777}p.excerpt.svelte-mnabfq{font-style:italic;margin-top:0.2rem;padding-left:4px;max-width:37rem}",
  map: '{"version":3,"file":"blog.svelte","sources":["blog.svelte"],"sourcesContent":["<script context=\\"module\\">\\n  import { base } from \\"$app/paths\\";\\n\\n  export async function load({ fetch }) {\\n    const posts = await fetch(`${base}/blog.json`).then((r) => r.json());\\n    return {\\n      props: { posts },\\n    };\\n  }\\n<\/script>\\n\\n<script>\\n  export let posts;\\n<\/script>\\n\\n<svelte:head>\\n  <title>kylieis.online \xB7 Blog</title>\\n</svelte:head>\\n\\n<h1>Blog</h1>\\n<h4>Long-form Twitter.</h4>\\n\\n{#each posts as post}\\n  <div class=\\"blog-card\\">\\n    <a href={`${base}/${post.slug}`}>\\n      <h2 class=\\"title\\">{post.metadata.title}</h2>\\n      <p class=\\"labels\\">\\n        {post.metadata.date.toUpperCase()}\\n        {post.metadata.category ? ` \xB7  ${post.metadata.category}` : \\"\\"}\\n      </p>\\n      <p class=\\"excerpt\\">{post.metadata.excerpt}</p>\\n    </a>\\n  </div>\\n{/each}\\n\\n<style lang=\\"scss\\">h2.title {\\n  margin-top: 2rem;\\n  margin-bottom: 0.4rem;\\n}\\nh2.title:hover {\\n  color: #f58b12;\\n}\\n\\nh4 {\\n  font-size: 17px;\\n  color: #555;\\n}\\n\\n.labels {\\n  display: flex;\\n  font-size: 13.5px;\\n  margin-top: 0px;\\n  padding: 1px 0 0 4px;\\n}\\n\\n.blog-card.last {\\n  padding-bottom: 6.5rem;\\n}\\n\\np {\\n  color: #777;\\n}\\n\\np.excerpt {\\n  font-style: italic;\\n  margin-top: 0.2rem;\\n  padding-left: 4px;\\n  max-width: 37rem;\\n}</style>\\n"],"names":[],"mappings":"AAmCmB,EAAE,MAAM,cAAC,CAAC,AAC3B,UAAU,CAAE,IAAI,CAChB,aAAa,CAAE,MAAM,AACvB,CAAC,AACD,EAAE,oBAAM,MAAM,AAAC,CAAC,AACd,KAAK,CAAE,OAAO,AAChB,CAAC,AAED,EAAE,cAAC,CAAC,AACF,SAAS,CAAE,IAAI,CACf,KAAK,CAAE,IAAI,AACb,CAAC,AAED,OAAO,cAAC,CAAC,AACP,OAAO,CAAE,IAAI,CACb,SAAS,CAAE,MAAM,CACjB,UAAU,CAAE,GAAG,CACf,OAAO,CAAE,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,AACtB,CAAC,AAMD,CAAC,cAAC,CAAC,AACD,KAAK,CAAE,IAAI,AACb,CAAC,AAED,CAAC,QAAQ,cAAC,CAAC,AACT,UAAU,CAAE,MAAM,CAClB,UAAU,CAAE,MAAM,CAClB,YAAY,CAAE,GAAG,CACjB,SAAS,CAAE,KAAK,AAClB,CAAC"}'
};
async function load$1({ fetch: fetch2 }) {
  const posts = await fetch2(`${base}/blog.json`).then((r) => r.json());
  return { props: { posts } };
}
const Blog = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { posts } = $$props;
  if ($$props.posts === void 0 && $$bindings.posts && posts !== void 0)
    $$bindings.posts(posts);
  $$result.css.add(css$1);
  return `${$$result.head += `${$$result.title = `<title>kylieis.online \xB7 Blog</title>`, ""}`, ""}

<h1>Blog</h1>
<h4 class="${"svelte-mnabfq"}">Long-form Twitter.</h4>

${each(posts, (post) => `<div class="${"blog-card"}"><a${add_attribute("href", `${base}/${post.slug}`, 0)}><h2 class="${"title svelte-mnabfq"}">${escape(post.metadata.title)}</h2>
      <p class="${"labels svelte-mnabfq"}">${escape(post.metadata.date.toUpperCase())}
        ${escape(post.metadata.category ? ` \xB7  ${post.metadata.category}` : "")}</p>
      <p class="${"excerpt svelte-mnabfq"}">${escape(post.metadata.excerpt)}</p></a>
  </div>`)}`;
});
var blog = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  "default": Blog,
  load: load$1
});
var _slug__svelte_svelte_type_style_lang = ".post.svelte-14ss73z{padding-bottom:3.8rem}h1.title.svelte-14ss73z{margin:1.6rem 0 0 0}p.date.svelte-14ss73z{color:#777;font-size:14.5px;margin:0.6rem 0 2.6rem 0;padding:1px 0 0 4px}";
const css = {
  code: ".post.svelte-14ss73z{padding-bottom:3.8rem}h1.title.svelte-14ss73z{margin:1.6rem 0 0 0}p.date.svelte-14ss73z{color:#777;font-size:14.5px;margin:0.6rem 0 2.6rem 0;padding:1px 0 0 4px}",
  map: '{"version":3,"file":"[slug].svelte","sources":["[slug].svelte"],"sourcesContent":["<script context=\\"module\\">\\n  import { base } from \\"$app/paths\\";\\n\\n  export async function load({ page, fetch }) {\\n    const slug = page.params.slug;\\n    const post = await fetch(`${base}/${slug}.json`).then((r) => r.json());\\n    return {\\n      props: { post },\\n    };\\n  }\\n<\/script>\\n\\n<script>\\n  export let post;\\n  let date = post.metadata.date.toUpperCase();\\n<\/script>\\n\\n<svelte:head>\\n  <title>{post.metadata.title}</title>\\n</svelte:head>\\n\\n<div class=\\"post\\">\\n  <h1 class=\\"title\\">{post.metadata.title}</h1>\\n  <p class=\\"date\\">{date}</p>\\n  {@html post.content}\\n</div>\\n\\n<style lang=\\"scss\\">.post {\\n  padding-bottom: 3.8rem;\\n}\\n\\nh1.title {\\n  margin: 1.6rem 0 0 0;\\n}\\n\\np.date {\\n  color: #777;\\n  font-size: 14.5px;\\n  margin: 0.6rem 0 2.6rem 0;\\n  padding: 1px 0 0 4px;\\n}</style>\\n"],"names":[],"mappings":"AA2BmB,KAAK,eAAC,CAAC,AACxB,cAAc,CAAE,MAAM,AACxB,CAAC,AAED,EAAE,MAAM,eAAC,CAAC,AACR,MAAM,CAAE,MAAM,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,AACtB,CAAC,AAED,CAAC,KAAK,eAAC,CAAC,AACN,KAAK,CAAE,IAAI,CACX,SAAS,CAAE,MAAM,CACjB,MAAM,CAAE,MAAM,CAAC,CAAC,CAAC,MAAM,CAAC,CAAC,CACzB,OAAO,CAAE,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,AACtB,CAAC"}'
};
async function load({ page, fetch: fetch2 }) {
  const slug = page.params.slug;
  const post = await fetch2(`${base}/${slug}.json`).then((r) => r.json());
  return { props: { post } };
}
const U5Bslugu5D = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { post } = $$props;
  let date = post.metadata.date.toUpperCase();
  if ($$props.post === void 0 && $$bindings.post && post !== void 0)
    $$bindings.post(post);
  $$result.css.add(css);
  return `${$$result.head += `${$$result.title = `<title>${escape(post.metadata.title)}</title>`, ""}`, ""}

<div class="${"post svelte-14ss73z"}"><h1 class="${"title svelte-14ss73z"}">${escape(post.metadata.title)}</h1>
  <p class="${"date svelte-14ss73z"}">${escape(date)}</p>
  <!-- HTML_TAG_START -->${post.content}<!-- HTML_TAG_END -->
</div>`;
});
var _slug_ = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  [Symbol.toStringTag]: "Module",
  "default": U5Bslugu5D,
  load
});
export { init, render };
